version: "3.7"

services:
  database:
    image: postgres
    container_name: database_node
    restart: allways
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=database_node
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: node_ts
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
